### ISSUE TITLE
error when generate synthetic data

### ISSUE THREAD

**Issue by dickyaz** [LLNL/tdmtpy#6]
Hi, I was trying the example code and I bump into error when run the code 02_Prepare_Data_and_Synthetic_for_Inversion.
Here is the error, seems like it fails to generate the synthetic data, because the hprep96, hspec96, hpulse96, f96tosac is not recognize Thank you.

`'hprep96' is not recognized as an internal or external command,
operable program or batch file.
'hspec96' is not recognized as an internal or external command,
operable program or batch file.
'hpulse96' is not recognized as an internal or external command,
operable program or batch file.
'f96tosac' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/User/Documents/PycharmProjects/SAMBOJA/mttime/examples/notebooks/02_Prepare_Data_and_Synthetics_For_Inversion.py", line 154, in <module>
    tmp = read(sacin,format="SAC")
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\obspy\core\util\decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\obspy\core\stream.py", line 212, in read
    st = _generic_reader(pathname_or_url, _read, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\obspy\core\util\base.py", line 700, in _generic_reader
    raise IOError(2, "No such file or directory", pathname)
FileNotFoundError: [Errno 2] No such file or directory: 'B00101ZDD.sac'`

**Comment by ahchiang** [comment]
You will need to install Computer Programs in Seismology to generate the synthetic Green’s functions http://www.eas.slu.edu/eqc/eqccps.html
